### ISSUE TITLE
Internal Workflow Process

### ISSUE THREAD

**Issue by shawnmclean** [SRoddis/Mongo.Migration#1]
Hi,

Nice library. 

Could you provide an outline of what happens during a migration?

From what I understand, it watches for reads from the mongo driver, check the version, run the migration (up/down) but then I'm not sure if it updates the document in mongo or just sends that conversion back to the consumer.

**Comment by shawnmclean** [comment]
Just read that updates are not handled.

**Comment by SRoddis** [comment]
At the moment the document is migrated and given back to the consumer. In the next release a automatically update on the database is planned. 

But I have to check the performance, because mongodb is optimated to read and not to write. That could be an issue. I think I will make a attributen to toggle it on for specific documents.

Cheers!
