### ISSUE TITLE
Rollback migrations

### ISSUE THREAD

**Issue by Almarein** [SRoddis/Mongo.Migration#15]
Hello!

Thanks for your application.

May be I'm not so good in search, but I cannot find a way to rollback migration in attached documentation. Could you provide me the right way to do this.
And another question - do you application provide possibility to rollback to initial version of document in database (document without version field) or we must add field to document that will contain initial version number?

Thanks!

**Comment by SRoddis** [comment]
Hey Almarein,

you just need to deploy your application and change the "RunTimeVersion" or "StartUpVersion" Annotation back to the version you want. If you dont use fast forward deployment, then you need to deploy the migrations in a seperat projekt. Otherwise the "down" migration will not exist, because it does not exist in the version of you application.

I will add a section to the documentation. 

Thanks for the question. 
Tell me if you need any further help.

Cheers, Sean

**Comment by SRoddis** [comment]
Hey glennsills,

Mongo.Migration is for simple schema migrations that could be done in runtime. At the moment there is no dependency injection for migrations planned. Iam worried, that this can decrease the performance. Maybe i have to split the mirgations between startup and runtime,  so in future its possible to do this on startup. I will have to think about this.

Logging will be added in the next version.

Cheers, Sean

**Comment by Almarein** [comment]
Thank you! This works.
