### ISSUE TITLE
Other function

### ISSUE THREAD

**Issue by esleybonomo** [SRoddis/Mongo.Migration#22]
Do you intend to implement the following functions?
- Migration to create (Up) or remove (Down) collection
- Migration to rename (Up / Down) collection
- Migration to insert default documents into collections

Because from what I saw, migration only works if there are documents in it, right?

**Comment by SRoddis** [comment]
Hey @esleybonomo, sorry for late response. I had a lot of work the last months.

Can you give me a little more information to you mentioned points?

- Migration to create (Up) or remove (Down) collection
-> Do you want to remove a whole collection? Create should work with your entities and repositories. So there is no migration needed. Remove makes sense I think.

- Migration to insert default documents into collections
-> I don't really get the point. Same point as create a collection. When you create your collection over a repository/Client, then you can add documents/entities as usual. Migrations should only be needed if you change your schema on the database.

- Because from what I saw, migration only works if there are documents in it, right?
-> The migrations should ignore empty collections. So I check if that is a bug.

Please give me some feedback.

Cheers,
Sean
